version: '3.5'

services:

  db_auth:
    container_name: db_auth
    ports:
      - "6001:6001"
    env_file:
      - ./back/.env
    image: postgres:16-alpine
    command:
      - "postgres"
      - "-c"
      - "port=6001"
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge